---
title: "Spatial Hotspots and Seasonal Shifts in Juvenile Loggerhead Sea Turtle Telemetry Data (2002–2005)"
https://github.com/uilliam-c/Connolly_Liam_ENE872_FinalProject
author: "Liam Connolly"
output: bookdown::pdf_document2
  toc: false
    number_selections: true
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# Load your packages
library(tidyverse)
library(lubridate)
# Set your ggplot theme
theme_set(theme_bw())
# Load your datasets
turtle_points <- readr::read_csv("../data_raw/turtlepoints.csv",
  show_col_types = FALSE)

modifiedturtle_points <- turtle_points %>%
  mutate(date_time =ymd_hms(date_time, tz = "UTC"),
  month = month(date_time), 
  season = ifelse(month %in% c(12, 1, 2), "Winter",
           ifelse(month %in% c(3, 4, 5), "Spring",
           ifelse(month %in% c(6, 7, 8), "Summer", "Fall"))),
  season = factor(season, levels = c("Winter", "Spring", "Summer", "Fall")),
  classitem = factor(classitem)) %>%
  filter(!is.na(latitude), !is.na(longitude), !is.na(date_time))
```


# Rationale and Research Questions
According to the online database, from which I collected my data, juvenile 
loggerhead turtles (Caretta caretta) move around frequently. Due to their 
juvenile phase of life, they are highly mobile yet, what isn't known is how or 
why they move to certain places in different seasons or ocean regions. 
From a spatial perspective, we don't have answers. Being able to identify where 
and when these turtles move/are found can help better understand their habitats.
It would be awesome to discover "hotspots" of more concentrated turtle presence 
as that may guide additional ecological analyses in the future. With the data 
available, it should be possible to assemble a general sense of the spatial 
patterns these loggerheads exhibit.

The background of this dataset relies on using satellite tracking locations
where each record present is indicative of a geo-referenced observation of a 
juvenile loggerhead. Each record comes with latitude/longitude, an individual 
identifier (series_id), and a timestamp (date_time). It is likely the dataset
will include repeated observations from the same loggerhead over the course of
the study (2002-2005), the data is still relevant for basic analyses. I will be 
focusing on examing seasonal distribution and spatial concentration for the 
loggerheads. Finally, the data contains a location "class" code (classitem) and 
some precision fields to help evaluate the patterns of data quality. 

Research Topic 1) Seasonal distribution Shifts
Research Question: Do juvenile loggerhead sea turtle locations (latitude)
differ among seasons (Winter, Spring, Summer, Fall)?
Hypothesis: Mean latitude differs among seasons.
Rationale for hypothesis: By nature, seasonal changes in ocean conditions such 
as temperature, current direction, etc should influence where juvenile turtles 
are found. If this were true that juvenile loggerheads go to different places
throughout the year, or if observation density varies by the different seasons
in varying areas, then there should be differences in latitude 
among seasons.

Research Topic 2) Spatial Hotspots of Presence
Research Question : Are loggerhead turtles locations concentrated in a few 
specific geographic areas (“Hotspots”) or are they more evenly distributed?
Hypothesis: The locations are spatially clustered, with a small amount of 
places accounting for a disproportionate amount of loggerhead observations.
Rationale: It isn't uncommon for animals, when they find a favorable place to 
live with good food availability or water temperature, to appear repeatedly in 
the same area. Therefore, if I can discover repeated observations of 
loggerheads in the same types of areas, it should allow for the creation of 
measurable hotspots in a spatial setting.

Research Topic 3) Data quality Differences by Location Class
Research Question: Do the categories in classitem correspond with 
differences in reported location precision (lprecision), and what would that
imply for interpreting spatial patterns?
Hypothesis: At least one classitem category has a different mean/median 
lprecision than the others
Rationale: While examining the dataset, I came across the columns with largely
unexplained categorical code (I think its categorical) that wasn't mentioned
anywhere in the public database. Those codes being classitem, and precision 
fields lprecision andtprecision. Upon consulting the metadata, it didn't 
mention what those fields meant either. Precision would naturally be relevant 
to examining hotspots as positioning would impact spatial clustering so I 
am curious if precision differs across classitem categories.  
\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
